# general settings
name: Enhancement_RetinexFormer_LOL_v2_real
model_type: ImageCleanModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 100

# load pre-trained encoder model
Pretrained_encoder:
  encoder_checkpoint: "pretrained_weights/encoder_LOLv2_real_30.83.pth"
  freeze_encoder: true

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: data/LOLv2/Real_captured/Train/Normal
    dataroot_lq: data/LOLv2/Real_captured/Train/Low
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8

    ### -------------Progressive training--------------------------
    # mini_batch_sizes: [8,5,4,2,1,1]             # Batch size per gpu   
    # iters: [46000,32000,24000,18000,18000,12000]
    # gt_size: 384   # Max patch size for progressive training
    # gt_sizes: [128,160,192,256,320,384]  # Patch sizes for progressive training.
    # ### ------------------------------------------------------------

    ### ------- Training on single fixed-patch size 128x128---------
    mini_batch_sizes: [8]   
    iters: [300000]
    gt_size: 192
    gt_sizes: [192]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: data/LOLv2/Real_captured/Test/Normal
    dataroot_lq: data/LOLv2/Real_captured/Test/Low
    io_backend:
      type: disk
      


# network structures
network_g:
  type: Retinex_Degradationv2

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~


# training settings
train:
  total_iter: 90000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles. 
  # 1st cycle: fixed 3e-4 LR for 92k iters. 
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [30000, 60000]
    restart_weights: [1,1]
    eta_mins: [0.0001, 0.000001]
  
  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: Adam
    lr: !!float 2e-4
    # weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: Smooth_L1Loss
    loss_weight: 1
    reduction: mean

  KL_loss_opt:
    type: KLLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 4
  val_freq: !!float 1e3
  save_img: false
  rgb2bgr: true
  use_image: false
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings

logger:
  print_freq: 1000  # 每 1000 个迭代打印一次日志信息
  save_checkpoint_freq: !!float 4e3  # 每 1000 个迭代保存一次模型检查点
  use_tb_logger: true  # 启用 TensorBoard 日志记录器
  wandb:
    project: low_light  # WandB 项目的名称
    resume_id: ~  # WandB 的恢复 ID，~ 表示没有指定

# dist training settings
dist_params:
  backend: nccl
  port: 29500
